---
kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: golang:1.18
    pull: if-not-exists
    commands:
      - go clean -testcache
      - go test ./... -v

  - name: build
    image: goreleaser/goreleaser
    pull: if-not-exists
    commands:
      - goreleaser build --snapshot --rm-dist

  - name: push
    image: thegeeklab/drone-docker-buildx
    privileged: true
    pull: if-not-exists
    settings:
      registry: ttl.sh
      repo: ttl.sh/93500dc3-168c-46e5-b2d6-a689da3d72c7
      tags:
       - 10m
      platforms:
        - linux/amd64
        - linux/arm64
      context: dist