stages:
  - test
  - build
  - push

variables:
  KO_DOCKER_REPO: "registry.gitlab.com/${GITLAB_USER_ID}/go-hello-world"

test:
  stage: test
  image:
    name: golang:1.19
    pull_policy: if-not-present
    entrypoint: [""]
  script:
    - go test -v ./...

ko_build:
  stage: push
  image:
    name: docker.io/kameshsampath/kube-dev-tools:0.1.5
    pull_policy: if-not-present
    entrypoint: [""]
  before_script:
    - echo "$CI_JOB_TOKEN" | ko auth login registry.gitlab.com -u "${GITLAB_USER_ID}" --password-stdin
  script:
    - ko build --bare --tags "$CI_COMMIT_SHORT_SHA" .

  