stages:
  - test
  - push

variables:
  KO_DOCKER_REPO: "registry.gitlab.com/${GITLAB_USER_NAME}/go-hello-world"

test:
  image:
    name: golang:1.19
    entrypoint: [""]
  script:
    - go test -v ./...

push:
  image:
    name: cgr.dev/chainguard/ko
    entrypoint: [""]
  before_script:
    - echo "$CI_JOB_TOKEN" | ko auth login registry.gitlab.com ${GITLAB_USER_NAME} --password-stdin
  script:
    - ko build --bare --tag "$CI_COMMIT_SHORT_SHA" .

  